### ISSUE TITLE
Hi, ROBO i need some help

### ISSUE THREAD

**Issue by TJAZZXL** [robojumper/DarkestDungeonSaveReader#2]
I am a switch user and have been playing the DD. Its a little hard for me so i decided to edit my save data. I soon found out all the save files are encrypted and i found this program you made. I have been trying to use it since yesterday and no luck so far. Maybe i am using it worng? Can you please tell me how does it work? I have the profile folder and DDSaveReader with me then what do i do. Thank you so much.

**Comment by robojumper** [comment]
I have not tested this tool with save files from any other platform than Windows. It would be very helpful if you could send me your profile folder in some way so I can check if it works and what changes are potentially needed.

-------------------------------------------------

The general instructions are essentially:

* Install Java 8+
* Open a command line
* Run the following to decode (for example) persist.estate.json

(adjust the path)

    java -jar DDSaveReader.jar -o decoded.json "D:\Steam\userdata\159746967\262060\remote\profile_3\persist.estate.json"

To save again, run

    java -cp DDSaveReader.jar de.robojumper.ddsavereader.file.Json2Dson -o "D:\Steam\userdata\159746967\262060\remote\profile_3\persist.estate.json" decoded.json

**Comment by TJAZZXL** [comment]
This is my save from switch and i will try the method you showed me. Thanks a bunch!
[profile_0.zip](https://github.com/robojumper/DarkestDungeonSaveReader/files/2177176/profile_0.zip)

**Comment by TJAZZXL** [comment]
I just tried it on my switch and it works like a charm. Thanks again for the program.
